/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'tutorial',
      label: '技術筆記',
    },
    {
      type: 'category',
      label: '封存 · 課程筆記',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: '測繪工程',
          collapsed: true,
          items: [
            'uni-notes/2019-09-02-cadastral-surveying-introduction',
            'uni-notes/2019-09-06-land-ownership-investigation',
            'uni-notes/2019-10-30-cadastral-surveying-exercises',
            'uni-notes/2019-11-26-surveying-paper-translation',
            'uni-notes/2019-12-18-geographic-information-system',
            'uni-notes/2020-02-24-satellite-navigation-principles',
            'uni-notes/2020-02-26-time-system',
          ],
        },
        {
          type: 'category',
          label: '影像處理',
          collapsed: true,
          items: [
            'uni-notes/2020-02-25-image-processing-1',
            'uni-notes/2020-03-04-image-basic-operations',
            'uni-notes/2020-03-10-image-enhancement-overview',
            'uni-notes/2020-03-12-image-restoration',
          ],
        },
        {
          type: 'category',
          label: '資料庫',
          collapsed: true,
          items: [
            'uni-notes/2018-09-06-database-system-overview-part1',
            'uni-notes/2018-09-06-database-system-overview-part2',
            'uni-notes/2018-10-26-sql-notes',
            'uni-notes/2018-12-18-database-experiments',
          ],
        },
        {
          type: 'category',
          label: '財政學',
          collapsed: true,
          items: [
            'uni-notes/2018-09-08-public-finance-intro',
            'uni-notes/2018-09-22-financial-expenditure-intro',
            'uni-notes/2018-09-22-public-finance-object-part1',
            'uni-notes/2018-09-22-public-finance-object-part2',
            'uni-notes/2019-01-01-public-finance-summary',
          ],
        },
        {
          type: 'category',
          label: '數位地形測量學',
          collapsed: true,
          items: [
            'uni-notes/2018-09-04-chapter1-coordinate-system-part1',
            'uni-notes/2018-09-04-coordinate-system-part2',
            'uni-notes/2018-09-16-coordinate-system-part3',
            'uni-notes/2019-03-03-measurement-error-theory',
          ],
        },
        {
          type: 'category',
          label: '金融市場與投資',
          collapsed: true,
          items: [
            'uni-notes/2018-09-10-financial-engineering-intro',
            'uni-notes/2018-09-15-financial-market-overview',
            'uni-notes/2018-09-16-financial-engineering-methodology',
            'uni-notes/2018-09-24-money-market',
            'uni-notes/2018-10-22-bond-market',
            'uni-notes/2019-04-02-international-balance-of-payments',
            'uni-notes/2019-04-03-macroeconomic-policy-practice',
            'uni-notes/2019-07-09-commercial-bank-introduction',
            'uni-notes/2019-07-19-bank-wealth-management-paper',
            'uni-notes/2019-09-08-central-banking-system',
            'uni-notes/2019-09-26-bank-wealth-management-paper-research',
            'uni-notes/2020-08-09-seaborn-visualization',
          ],
        },
        {
          type: 'category',
          label: '財務報表分析',
          collapsed: true,
          items: [
            'uni-notes/2018-09-16-financial-statement-analysis-intro',
            'uni-notes/2018-09-23-financial-statement-analysis-basics',
          ],
        },
        {
          type: 'category',
          label: '資料結構',
          collapsed: true,
          items: [
            'uni-notes/2019-03-03-data-structure-introduction',
            'uni-notes/2019-03-04-linear-list',
            'uni-notes/2019-03-23-string-implementation',
          ],
        },
        {
          type: 'category',
          label: '地圖學',
          collapsed: true,
          items: [
            'uni-notes/2019-07-20-maps-and-cartography-basics',
            'uni-notes/2019-07-21-map-language',
          ],
        },
        {
          type: 'category',
          label: '程式設計與開發',
          collapsed: true,
          items: [
            'uni-notes/2019-01-13-scrapy',
            'uni-notes/2019-03-19-opengl-drawing',
            'uni-notes/2019-05-28-computer-graphics',
            'uni-notes/2019-09-12-vue-hello-world',
            'uni-notes/2020-05-07-ml-cv-concepts',
            'uni-notes/2020-11-17-color-driven-motor',
          ],
        },
        {
          type: 'category',
          label: '其他',
          collapsed: true,
          items: [
            'uni-notes/2018-09-03-introduction',
            'uni-notes/2018-09-06-city-urbanization',
            'uni-notes/2018-10-08-hong-kong-trip',
            'uni-notes/2019-03-23-insurance-contract',
            'uni-notes/2020-02-24-circuits-1-1',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '嵌入式系統',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Telink',
          collapsed: false,
          items: [
            'embedded/telink/tlsr8258/sws-build-flash-verify'
          ]
        },
        {
          type: 'category',
          label: 'Bouffalo Lab 與 WinnerMicro',
          collapsed: true,
          items: [
            'micro-controladores/CN/bouffalo_sdk',
            'micro-controladores/CN/warning_uart_rts',
            'micro-controladores/CN/bouffalo-BL602-AI-WB2-32s',
            'micro-controladores/CN/bouffalo-BL616-AI-M62-32s',
            'micro-controladores/CN/bouffalo-BL618-Sipeed-M0P-Dock',
            'micro-controladores/CN/winnermicro-XT-E804-HLK-W801-Kit'
          ]
        },
        {
          type: 'category',
          label: 'STM32',
          collapsed: true,
          items: [
            'micro-controladores/STM32/stm32_cdc_develop'
          ]
        },
        {
            type: 'category',
            label: 'ESP32',
            collapsed: true,
            items: [
              'micro-controladores/ESP32/esp-idf5.3_sdk',
              'micro-controladores/ESP32/esp32-adf-I2S',
              'micro-controladores/ESP32/esp32-encoder',
              'micro-controladores/ESP32/esp32_all_need_know_zh_hk',
              'micro-controladores/ESP32/esp32_all_need_know',
              'micro-controladores/ESP32/esp32-mcpwm-usage-and-examples',
              'micro-controladores/ESP32/esp32-rf24-demo',
              'micro-controladores/ESP32/esp32-zephyer-basic',
              'micro-controladores/ESP32/esp32-lol'
            ]
        },
        {
            type: 'category',
            label: 'RP2040',
            collapsed: true,
            items: [
              'micro-controladores/RP2040/rp2040-uart-interrupt-handling-and-usage',
              'micro-controladores/RP2040/rp2040-pwm-usage-and-examples',
              'micro-controladores/RP2040/rp2040-timer-and-alarm-usage',
              'micro-controladores/RP2040/mastering-pio-programming',
              'micro-controladores/RP2040/pio-uart-implementation',
              'micro-controladores/RP2040/advanced-pio-led-control-and-resource-management',
              'micro-controladores/RP2040/rp2040-rf24-demo',
              'micro-controladores/RP2040/rp2040-lol'
            ]
        },
        {
          type: 'category',
          label: 'Wireless · Bluetooth',
          collapsed: true,
          items: [
            'comunicaciones/Bluetooth/basics',
            'comunicaciones/Bluetooth/hack_esp'
          ]
        }
      ]
    },
    {
      type: 'category',
      label: '封存 · 舊文章',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Linux & System Administration',
          collapsed: true,
          items: [
            'migrated/linux-commands-complete-reference',
            'migrated/linux-commands-complete-guide',
            'migrated/common-linux-commands-detailed-guide',
            'migrated/common-linux-commands-part-1',
            'migrated/sed-text-processing-complete-guide',
            'migrated/shell-scripting-programming-guide',
            'migrated/linux-disk-space-cleanup',
            'migrated/linux-firewall-management-guide',
            'migrated/ubuntu-kvm-virtualization-guide'
          ]
        },
        {
          type: 'category',
          label: 'Docker & DevOps',
          collapsed: true,
          items: [
            'migrated/docker-getting-started-guide',
            'migrated/docker-usage-guide-part-1',
            'migrated/docker-usage-guide-part-2',
            'migrated/docker-machine-learning-environment-setup',
            'migrated/kubernetes-installation-and-configuration'
          ]
        },
        {
          type: 'category',
          label: 'Programming Languages',
          collapsed: true,
          items: [
            'migrated/golang-complete-learning-guide',
            'migrated/golang-learning-guide',
            'migrated/git-complete-usage-guide',
            'migrated/git-usage-guide',
            'migrated/python-gmail-sending-guide',
            'migrated/python-notes-and-tips',
            'migrated/qt5-standard-library-guide',
            'migrated/pyqt5-qgraphicsview-complete-guide',
            'migrated/pyqt5-qgraphics-guide'
          ]
        },
        {
          type: 'category',
          label: 'Data Science & Machine Learning',
          collapsed: true,
          items: [
            'migrated/xgboost-stock-price-prediction-guide',
            'migrated/pytorch-stock-prediction-guide',
            'migrated/matlab-robotics-simulation-guide',
            'migrated/conda-installation-and-usage',
            'migrated/google-colab-usage-tips'
          ]
        },
        {
          type: 'category',
          label: 'Web Development & APIs',
          collapsed: true,
          items: [
            'migrated/jin10-financial-news-scraping-guide',
            'migrated/cryptocurrency-scraping-colly-guide',
            'migrated/heroku-flask-deployment-complete-guide',
            'migrated/gcp-python-flask-deployment-guide',
            'migrated/heroku-selenium-web-scraping-guide',
            'migrated/chrome-selenium-headless-setup-guide'
          ]
        },
        {
          type: 'category',
          label: 'Tools & Testing',
          collapsed: true,
          items: [
            'migrated/apache-benchmark-comprehensive-guide',
            'migrated/ab-stress-testing-guide',
            'migrated/tinybenchmark-reproduction-troubleshooting-guide',
            'migrated/opensearch-complete-guide'
          ]
        },
        {
          type: 'category',
          label: 'Embedded & Hardware',
          collapsed: true,
          items: [
            'migrated/raspberry-pi-pico-motor-control',
            'migrated/nvidia-driver-installation-guide',
            'migrated/openmmlab-mmtracking-guide',
            'migrated/openpose-debugging-guide'
          ]
        },
        {
          type: 'category',
          label: 'ROS & Robotics',
          collapsed: true,
          items: [
            'migrated/ros-filesystem-guide',
            'migrated/ros-package-development-guide'
          ]
        },
        {
          type: 'category',
          label: 'Blockchain & Security',
          collapsed: true,
          items: [
            'migrated/solidity-erc20-token-development-guide',
            'migrated/grafana-prometheus-complete-monitoring-guide'
          ]
        }
      ]
    }
  ]

};

export default sidebars;
