/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Tutorial',
      // items: ['esp/esp32c3-dev-get-start'],
      items:
      [
        {
          type: 'category',
          label: 'ESP',
          items: 
          [
            'esp/esp32c3-dev-get-start'
          ],  
        },
        {
          type: 'category',
          label: 'RP2040',
          items: 
          [
            'rp2040/freeRTOS-on-RP2040-get-start',
            'rp2040/PlatformIO-on-RP2040-get-start',
            'rp2040/micro-ROS-on-RP2040'
          ],  
        },
        {
          type: 'category',
          label: 'samd',
          items: 
          [
            'samd/Seeeduino_Lotus_Cortex-M0'
          ],  
        },
        {
          type: 'category',
          label: 'Software',
          items: 
          [
            'Software/terminator',
            'Software/docusaurus'   
          ],  
        },
        {
          type: 'category',
          label: 'ROS',
          items: 
          [
            'ROS/install_ros2_on_ubuntu'
          ],  
        },
        {
          type: 'category',
          label: 'Jetson',
          items: 
          [
            'Jetson/Get_Start_With_Nano'
          ],  
        },
      ],
    },
  ],

};

module.exports = sidebars;
