---
title: 非常糟糕的一次录音
date: 2018-12-23 22:03:22
tags:
---
{% aplayer "刚好遇见你 （独奏） 第一次吹 中间出现了错误 lol " "tianrking"
 "/root-images/ganghaoyujianni-p.mp3" "autoplay" %}

{% aplayer "刚好遇见你 （原曲伴奏） 手机录制的很大杂音没办法 " "tianrking"
 "/root-images/ganghaoyujianni.mp3" "autoplay" %}

 {% aplayer "天龙八部 竹笛部分 第一次吹 有些生疏 假期打算 录制一份完整的  " "tianrking"
 "/root-images/cqy.mp3" "autoplay" %}